name: Build OSX

on:
  push:
     branches:
        - main
     tags:
        - '*'

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           fetch-depth: 0

     - name: Determine VERSION
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION=$(git describe --tags "$(git rev-list --tags --max-count=1)")
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NEXTCLOUD_SCIEBO_PASSWORD: ${{ secrets.NEXTCLOUD_SCIEBO_PASSWORD }}
          NEXTCLOUD_SCIEBO_SHARE: ${{ secrets.NEXTCLOUD_SCIEBO_SHARE }}
        run: |
          npm run build --loglevel verbose

      - name: Upload Artifacts
        env:
          NEXTCLOUD_SCIEBO_PASSWORD: ${{ secrets.NEXTCLOUD_SCIEBO_PASSWORD }}
          NEXTCLOUD_SCIEBO_SHARE: ${{ secrets.NEXTCLOUD_SCIEBO_SHARE }}
        run: |
          curl -v -u "$NEXTCLOUD_SCIEBO_SHARE:$NEXTCLOUD_SCIEBO_PASSWORD" -T dist/Shiny-Calorie-${VERSION}-arm64.dmg https://uni-bonn.sciebo.de/public.php/webdav/Shiny-Calorie-${VERSION}-arm64.dmg

## Used previously to upload to github artifacts
#      - name: Upload Artifacts
#        if: success()
#        uses: actions/upload-artifact@v3
#        with:
#          name: electron-app-build
#          path: dist/ 
