name: Build Electron App

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger build on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Builds for Linux, Windows, macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass GitHub token as an environment variable
        run: |
          npm run build --loglevel verbose

          # Search for any log or txt files generated after the build process
          echo "Searching for error logs..."
          find /home/runner/.npm/_logs/ -name "*.log" -o -name "*.txt" | while read file; do
            echo "Found log file: $file"
            echo "Displaying contents of $file:"
            cat "$file"
          done

      # Upload artifacts (optional, if you want to keep the installers as part of the GitHub workflow)
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-build
          path: dist/  # Upload the dist folder containing installers
