name: Build Windows

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine VERSION
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION=$(git describe --tags "$(git rev-list --tags --max-count=1)")
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SCIEBO_ACCESS_TOKEN: ${{ secrets.NEXTCLOUD_SCIEBO_SHARE }}
          NEXTCLOUD_SCIEBO_SHARE: ${{ secrets.NEXTCLOUD_SCIEBO_SHARE }}
        run: |
          npm run build-win --loglevel verbose

      - name: Upload Artifacts
        if: success()
        env:
          SCIEBO_ACCESS_TOKEN: ${{ secrets.NEXTCLOUD_SCIEBO_PASSWORD }}
          NEXTCLOUD_SCIEBO_SHARE: ${{ secrets.NEXTCLOUD_SCIEBO_SHARE }}
          VERSION: ${{ github.ref_name }}
        run: |
           $username = $env:NEXTCLOUD_SCIEBO_SHARE
           $token = $env:SCIEBO_ACCESS_TOKEN
           $version = $env:VERSION
           $url = "https://uni-bonn.sciebo.de/public.php/webdav/Shiny-Calorie-${version}-amd64.exe"
           curl.exe -v -u "${username}:${token}" -X PUT -T "dist\Shiny-Calorie Setup ${version}.exe" $url
