name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Snapcraft
        run: |
          sudo apt-get update 
          sudo apt-get install snapd
          sudo snap install snapcraft --classic

      - name: Build Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SCIEBO_ACCESS_TOKEN: ${{ secrets.NEXTCLOUD_SCIEBO_PASSWORD }}
          NEXTCLOUD_SCIEBO_SHARE: ${{ secrets.NEXTCLOUD_SCIEBO_SHARE }}
        run: |
          npm run build-linux --loglevel verbose

      - name: Upload Artifacts
        if: success()
        env:
          SCIEBO_ACCESS_TOKEN: ${{ secrets.NEXTCLOUD_SCIEBO_PASSWORD }}
          NEXTCLOUD_SCIEBO_SHARE: ${{ secrets.NEXTCLOUD_SCIEBO_SHARE }}
          APP_VERSION: ${{ github.ref_name }}
        run: |
          curl -v -u "$NEXTCLOUD_SCIEBO_SHARE:$SCIEBO_ACCESS_TOKEN" -T dist/Shiny-Calorie-1.0.0.AppImage https://uni-bonn.sciebo.de/public.php/webdav/Shiny-Calorie-1.0.0-amd64.AppImage
          curl -v -u "$NEXTCLOUD_SCIEBO_SHARE:$SCIEBO_ACCESS_TOKEN" -T dist/Shiny-Calorie_1.0.0_amd64.snap https://uni-bonn.sciebo.de/public.php/webdav/Shiny-Calorie-1.0.0-amd64.snap

