name: Build OSX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SCIEBO_ACCESS_TOKEN: ${{ secrets.PASSWORD_SCIEBO_SHARE }}
          SCIEBO_SHARE_NAME: ${{ secrets.SCIEBO_SHARE_NAME }}
        run: |
          npm run build --loglevel verbose

      - name: Upload Artifacts
        env:
          SCIEBO_ACCESS_TOKEN: ${{ secrets.PASSWORD_SCIEBO_SHARE }}
          SCIEBO_SHARE_NAME: ${{ secrets.SCIEBO_SHARE_NAME }}
        run: |
          curl -v -u "$NEXTCLOUD_SCIEBO_SHARE:$NEXTCLOUD_SCIEBO_PASSWORD" -T dist/MyElectronShinyApp-1.0.0-arm64.dmg https://uni-bonn.sciebo.de/public.php/webdav/MyElectronShinyApp-1.0.0-arm64.dmg

## Used previously to upload to github artifacts
#      - name: Upload Artifacts
#        if: success()
#        uses: actions/upload-artifact@v3
#        with:
#          name: electron-app-build
#          path: dist/ 
