name: Upload to Sciebo

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build artifact
        run: |
          # Your build steps here
          echo "Hello World!" > artifact.csv
      - name: Upload to Sciebo using Access Token
        env:
          SCIEBO_ACCESS_TOKEN: ${{ secrets.PASSWORD_SCIEBO_SHARE }}
          SCIEBO_SHARE_NAME: ${{ secrets.SCIEBO_SHARE_NAME }}
        run: |
          curl -v -u "$SCIEBO_SHARE_NAME:$SCIEBO_ACCESS_TOKEN" -T artifact.csv https://uni-bonn.sciebo.de/public.php/webdav/artifact.csv

